# Generated by Django 3.2.25 on 2025-07-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='price',
            new_name='charge',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='subscription_duration',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
