# Generated by Django 3.2.25 on 2025-07-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20250711_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='subscription_duration',
            new_name='duration_weeks',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='charge',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='stages',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='level',
            field=models.CharField(choices=[('alpha', 'Alpha'), ('beta', 'Beta'), ('gamma', 'Gamma')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
